(() => {
  function invoiceForm(clients) { return `<form class="form-grid"><div class="field"><label>العميل</label><select name="clientId" required><option value="">اختر</option>${clients.map(row => `<option value="${UI.escape(row['Client ID'])}">${UI.escape(row['Client Name'])}</option>`).join('')}</select></div><div class="field"><label>القيمة</label><input name="amount" type="number" min="0" step=".01" required></div><div class="field"><label>الضريبة</label><input name="taxAmount" type="number" min="0" step=".01" value="0"></div><div class="field"><label>تاريخ الإصدار</label><input name="issueDate" type="date" required></div><div class="field"><label>تاريخ الاستحقاق</label><input name="dueDate" type="date" required></div><div class="field"><label>الحالة</label><select name="status"><option>DRAFT</option><option>SENT</option></select></div><div class="wide actions"><button class="btn btn-primary" type="submit">إنشاء الفاتورة</button></div></form>`; }
  function accountForm() { return `<form class="form-grid"><div class="field"><label>اسم الحساب</label><input name="accountName" required></div><div class="field"><label>البنك</label><input name="bankName" required></div><div class="field"><label>رقم الحساب المقنّع</label><input name="accountNumberMasked" placeholder="**** 1234"></div><div class="field"><label>الرصيد الافتتاحي</label><input name="openingBalance" type="number" step=".01" value="0"></div><div class="wide actions"><button class="btn btn-primary" type="submit">إنشاء الحساب</button></div></form>`; }
  function depositForm(accounts) { return `<form class="form-grid"><div class="field"><label>الحساب</label><select name="bankAccountId" required>${accounts.map(row => `<option value="${UI.escape(row['Bank Account ID'])}">${UI.escape(row['Account Name'])}</option>`).join('')}</select></div><div class="field"><label>القيمة</label><input name="amount" type="number" min=".01" step=".01" required></div><div class="field wide"><label>الوصف</label><input name="description" value="إيداع بنكي"></div><div class="wide actions"><button class="btn btn-primary" type="submit">تسجيل الإيداع</button></div></form>`; }
  async function load() {
    const [invoiceData, paymentData, expenseData, accountData, clientData] = await Promise.all([API.get('invoices'),API.get('payments'),API.get('expenses'),API.get('bank.accounts'),API.get('clients')]);
    const invoiceTotal = invoiceData.invoices.reduce((s,row) => s + Number(row.Amount || 0) + Number(row['Tax Amount'] || 0),0);
    const paidTotal = paymentData.payments.reduce((s,row) => s + Number(row.Amount || 0),0);
    UI.setMain(`<section class="grid metrics">${UI.metric('إجمالي الفواتير',UI.money(invoiceTotal))}${UI.metric('التحصيل',UI.money(paidTotal))}${UI.metric('المتبقي',UI.money(invoiceTotal-paidTotal))}${UI.metric('الرصيد البنكي',UI.money(accountData.accounts.reduce((s,row)=>s+Number(row['Current Balance']||0),0)))}</section><section class="card"><div class="card-header"><h2>الحسابات البنكية</h2><div class="actions"><button class="btn" id="new-account">حساب جديد</button>${accountData.accounts.length ? '<button class="btn btn-primary" id="new-deposit">إيداع</button>' : ''}</div></div>${UI.table(accountData.accounts,[{key:'Account Name',label:'الحساب'},{key:'Bank Name',label:'البنك'},{key:'Account Number Masked',label:'الرقم'},{key:'Current Balance',label:'الرصيد',render:UI.money},{key:'Active',label:'نشط',render:UI.badge}])}</section><section class="card"><div class="card-header"><h2>الفواتير</h2><button class="btn btn-primary" id="new-invoice">فاتورة جديدة</button></div>${UI.table(invoiceData.invoices,[{key:'Invoice Number',label:'رقم الفاتورة'},{key:'Client ID',label:'العميل'},{key:'Issue Date',label:'الإصدار',render:UI.date},{key:'Due Date',label:'الاستحقاق',render:UI.date},{key:'Amount',label:'القيمة',render:UI.money},{key:'Status',label:'الحالة',render:UI.badge},{key:'Invoice ID',label:'PDF',render:v=>`<button class="btn" data-invoice-pdf="${UI.escape(v)}">إنشاء PDF</button>`}])}</section><section class="grid two"><article class="card"><div class="card-header"><h2>المدفوعات</h2></div>${UI.table(paymentData.payments,[{key:'Payment Date',label:'التاريخ',render:UI.date},{key:'Client ID',label:'العميل'},{key:'Amount',label:'القيمة',render:UI.money},{key:'Method',label:'الطريقة'}])}</article><article class="card"><div class="card-header"><h2>المصروفات</h2></div>${UI.table(expenseData.expenses,[{key:'Expense Date',label:'التاريخ',render:UI.date},{key:'Category',label:'التصنيف'},{key:'Amount',label:'القيمة',render:UI.money},{key:'Vendor',label:'المورّد'}])}</article></section>`);
    document.querySelectorAll('[data-invoice-pdf]').forEach(button=>button.addEventListener('click',async()=>{try{button.disabled=true;const pdf=await API.post('invoices.pdf',{invoiceId:button.dataset.invoicePdf});UI.toast('تم إنشاء ملف PDF.');window.open(pdf.url,'_blank','noopener');}catch(error){UI.toast(error.message,'error');}finally{button.disabled=false;}}));    function open(title, html, route) { const modal = UI.modal(title, html); const target = modal.querySelector('form'); target.addEventListener('submit', event => { event.preventDefault(); UI.submit(target, async data => { await API.post(route,data); UI.toast('تم حفظ العملية المالية.'); modal.remove(); load(); }); }); }
    document.querySelector('#new-account').addEventListener('click',()=>open('حساب بنكي جديد',accountForm(),'bank.accounts'));
    document.querySelector('#new-deposit')?.addEventListener('click',()=>open('تسجيل إيداع',depositForm(accountData.accounts),'bank.deposit'));
    document.querySelector('#new-invoice').addEventListener('click',()=>open('فاتورة جديدة',invoiceForm(clientData.clients),'invoices'));
  }
  ANCPageModules.finance = { load };
})();
