(() => {
  const statuses = ['TODO','IN_PROGRESS','IN_REVIEW','DONE','BLOCKED'];
  function form(projects, employees) { return `<form class="form-grid"><div class="field"><label>اسم المهمة</label><input name="taskName" required></div><div class="field"><label>المشروع</label><select name="projectId"><option value="">بدون مشروع</option>${projects.map(row => `<option value="${UI.escape(row['Project ID'])}">${UI.escape(row['Project Name'])}</option>`).join('')}</select></div><div class="field"><label>الأولوية</label><select name="priority"><option>MEDIUM</option><option>HIGH</option><option>URGENT</option><option>LOW</option></select></div><div class="field"><label>الموظف</label><select name="employeeId"><option value="">غير مسند</option>${employees.map(row => `<option value="${UI.escape(row['Employee ID'])}">${UI.escape(row['Full Name'])}</option>`).join('')}</select></div><div class="field"><label>موعد التسليم</label><input name="dueDate" type="date"></div><div class="field"><label>الساعات المقدرة</label><input name="estimatedHours" type="number" min="0" step=".5"></div><div class="field wide"><label>Brief</label><textarea name="brief"></textarea></div><div class="wide actions"><button class="btn btn-primary" type="submit">إنشاء المهمة</button></div></form>`; }
  async function load() {
    const [{ tasks, employees = [] }, projectResult] = await Promise.all([API.get('tasks'), API.get('projects').catch(() => ({projects:[]}))]);
    UI.setMain(`<section class="card"><div class="card-header"><div><h2>لوحة Kanban</h2><p class="muted">تابع حركة التنفيذ من التكليف حتى الإنجاز.</p></div>${projectResult.projects?.length ? '<button class="btn btn-primary" id="new-task">مهمة جديدة</button>' : ''}</div><div class="kanban">${statuses.map(status => `<section class="kanban-column"><div class="split-title"><strong>${status}</strong><span class="badge">${tasks.filter(row => row.Status === status).length}</span></div>${tasks.filter(row => row.Status === status).map(row => `<article class="kanban-card"><strong>${UI.escape(row['Task Name'])}</strong><p class="muted">${UI.escape(row.Assignee || 'غير مسند')}</p><div class="split-title">${UI.badge(row.Priority)}<small>${UI.date(row['Due Date'])}</small></div></article>`).join('') || UI.empty('لا توجد مهام')}</section>`).join('')}</div></section>`);
    document.querySelector('#new-task')?.addEventListener('click', () => { const modal = UI.modal('مهمة جديدة', form(projectResult.projects || [], employees)); const target = modal.querySelector('form'); target.addEventListener('submit', event => { event.preventDefault(); UI.submit(target, async data => { await API.post('tasks', data); UI.toast('تم إنشاء المهمة.'); modal.remove(); load(); }); }); });
  }
  ANCPageModules.operations = { load };
})();
