(() => {
  function bars(items, money = true) {
    if (!items?.length) return UI.empty();
    const max = Math.max(...items.map(item => Number(item.value) || 0), 1);
    return `<div class="chart">${items.slice(0,10).map(item => `<div class="chart-column"><div class="chart-bar" style="height:${Math.max(2,item.value/max*100)}%" title="${money ? UI.money(item.value) : UI.number(item.value)}"></div><div class="chart-label">${UI.escape(item.key)}</div></div>`).join('')}</div>`;
  }
  async function reports() {
    const [revenue, profitability, productivity, campaigns] = await Promise.all([API.get('reports.revenue'),API.get('reports.profitability'),API.get('reports.productivity'),API.get('reports.campaigns')]);
    UI.setMain(`<section class="grid two"><article class="card"><div class="card-header"><h2>الإيراد حسب العميل</h2></div>${bars(revenue.byClient)}</article><article class="card"><div class="card-header"><h2>الإيراد حسب المشروع</h2></div>${bars(revenue.byProject)}</article><article class="card"><div class="card-header"><h2>الربحية حسب العميل</h2></div>${bars(profitability.byClient)}</article><article class="card"><div class="card-header"><h2>أداء الموظفين</h2></div>${UI.table(productivity.employees,[{key:'employeeId',label:'الموظف'},{key:'total',label:'المهام'},{key:'done',label:'المكتمل'},{key:'completionRate',label:'نسبة الإنجاز',render:v=>`${UI.number(v)}%`}])}</article></section><section class="card"><div class="card-header"><h2>الإنفاق حسب المنصة</h2></div>${bars(campaigns.platforms)}</section>`);
  }
  async function profitability() {
    const [data, ads] = await Promise.all([API.get('reports.profitability'),API.get('ads')]);
    const total = ads.ads.reduce((sum,row)=>sum+Number(row.Profit||0),0);
    UI.setMain(`<section class="grid metrics">${UI.metric('إجمالي ربح الإعلانات',UI.money(total))}${UI.metric('إعلانات رابحة',ads.ads.filter(row=>Number(row.Profit)>0).length)}${UI.metric('تجاوزات الربح',ads.ads.filter(row=>row['Override Reason']).length)}${UI.metric('متوسط الربح',UI.money(ads.ads.length?total/ads.ads.length:0))}</section><section class="grid two"><article class="card"><div class="card-header"><h2>الربحية حسب العميل</h2></div>${bars(data.byClient)}</article><article class="card"><div class="card-header"><h2>الربحية حسب الحملة/المشروع</h2></div>${bars(data.byCampaign)}</article></section>`);
  }
  async function documents() {
    const [taskData, studioData] = await Promise.all([API.get('tasks'),API.get('studio.jobs')]);
    const links = studioData.jobs.filter(row=>row['Delivery URL']).map(row=>({name:row.Title,type:'Studio Delivery',url:row['Delivery URL'],date:row['Updated At']}));
    UI.setMain(`<section class="card"><div class="card-header"><div><h2>مركز المستندات والتسليمات</h2><p class="muted">روابط Google Drive محفوظة في سجلات الأعمال.</p></div><span class="badge">${links.length} رابط</span></div>${UI.table(links,[{key:'name',label:'المستند/التسليم'},{key:'type',label:'النوع',render:UI.badge},{key:'date',label:'آخر تحديث',render:UI.date},{key:'url',label:'الرابط',render:v=>`<a class="lime" href="${UI.escape(v)}" target="_blank" rel="noopener">فتح في Drive</a>`}])}</section><section class="card"><div class="card-header"><h2>المهام المرتبطة</h2></div>${UI.table(taskData.tasks,[{key:'Task Name',label:'المهمة'},{key:'Project ID',label:'المشروع'},{key:'Assignee',label:'المسؤول'},{key:'Status',label:'الحالة',render:UI.badge}])}</section>`);
  }
  async function alerts() {
    const data = await API.get('dashboard'); const m=data.metrics;
    const items=[m.lowProfitAds?{level:'خطر',title:'إعلانات تحت حد الربح',value:m.lowProfitAds}:null,m.overdueTasks?{level:'تحذير',title:'مهام متأخرة',value:m.overdueTasks}:null,m.outstanding>0?{level:'مالي',title:'مستحقات غير محصلة',value:UI.money(m.outstanding)}:null].filter(Boolean);
    UI.setMain(`<section class="card"><div class="card-header"><div><h2>مركز التنبيهات</h2><p class="muted">التنبيهات مستخرجة لحظيًا من مؤشرات التشغيل والمالية.</p></div><span class="badge ${items.length?'warning':'success'}">${items.length}</span></div>${items.length?`<div class="grid three">${items.map(item=>`<article class="alert danger"><span class="badge danger">${UI.escape(item.level)}</span><h3 style="margin-top:12px">${UI.escape(item.title)}</h3><div class="metric-value">${UI.escape(item.value)}</div></article>`).join('')}</div>`:'<div class="empty">لا توجد تنبيهات حرجة. كل المؤشرات ضمن الحدود.</div>'}</section>`);
  }
  async function status() {
    const health=await API.health();let diagnostics=null;try{diagnostics=await API.get('diagnostics');}catch{}
    UI.setMain(`<section class="grid metrics">${UI.metric('حالة الخدمة',UI.badge(health.status))}${UI.metric('الإصدار',UI.escape(health.version))}${UI.metric('المنطقة الزمنية',UI.escape(health.timezone))}${UI.metric('الإعداد',UI.badge(health.configured))}</section>${diagnostics?`<section class="card"><div class="card-header"><h2>أعداد السجلات</h2></div>${UI.table(Object.entries(diagnostics.counts).map(([name,count])=>({name,count})),[{key:'name',label:'الجدول'},{key:'count',label:'السجلات'}])}</section>`:''}`);
  }
  async function audit() { const data=await API.get('audit',{limit:200}); UI.setMain(`<section class="card"><div class="card-header"><div><h2>سجل التدقيق</h2><p class="muted">آخر ${data.entries.length} عملية من أصل ${data.total}.</p></div></div>${UI.table(data.entries,[{key:'Timestamp',label:'الوقت',render:UI.date},{key:'Actor',label:'المنفذ'},{key:'Action',label:'العملية',render:UI.badge},{key:'Entity Type',label:'النوع'},{key:'Entity ID',label:'المعرّف'},{key:'Details',label:'التفاصيل'}])}</section>`); }
  async function settings() {
    const result=await API.get('ads.settings');const s=result.settings;
    UI.setMain(`<section class="card"><div class="card-header"><div><h2>إعدادات الإعلانات</h2><p class="muted">تُطبق كقيم افتراضية ويمكن تجاوزها لكل إعلان.</p></div></div><form id="settings-form" class="form-grid"><div class="field"><label>Default Cost Rate</label><input name="Default Cost Rate" type="number" step=".0001" value="${UI.escape(s['Default Cost Rate'])}"></div><div class="field"><label>Default Commission Rate</label><input name="Default Commission Rate" type="number" step=".0001" value="${UI.escape(s['Default Commission Rate'])}"></div><div class="field"><label>Minimum Profit Amount</label><input name="Minimum Profit Amount" type="number" step=".01" value="${UI.escape(s['Minimum Profit Amount'])}"></div><div class="field"><label>Minimum Profit Margin %</label><input name="Minimum Profit Margin" type="number" step=".01" value="${UI.escape(s['Minimum Profit Margin'])}"></div><div class="field"><label>Default Currency</label><input name="Default Currency" value="${UI.escape(s['Default Currency'])}"></div><div class="field"><label>Default Bank Account ID</label><input name="Default Bank Account" value="${UI.escape(s['Default Bank Account'])}"></div><div class="field wide"><label><input name="Allow Negative Bank Balance" type="checkbox" ${String(s['Allow Negative Bank Balance']).toLowerCase()==='true'?'checked':''}> السماح برصيد بنكي سالب</label></div><div class="wide actions"><button class="btn btn-primary" type="submit">حفظ الإعدادات</button></div></form></section>`);
    const form=document.querySelector('#settings-form');form.addEventListener('submit',event=>{event.preventDefault();UI.submit(form,async data=>{if(!data['Allow Negative Bank Balance'])data['Allow Negative Bank Balance']=false;await API.post('ads.settings',data);UI.toast('تم حفظ الإعدادات.');});});
  }
  Object.assign(ANCPageModules,{reports:{load:reports},profitability:{load:profitability},documents:{load:documents},alerts:{load:alerts},status:{load:status},audit:{load:audit},settings:{load:settings}});
})();
