(() => {
  function form(clients, employees) { return `<form class="form-grid"><div class="field"><label>العميل</label><select name="clientId" required><option value="">اختر</option>${clients.map(row => `<option value="${UI.escape(row['Client ID'])}">${UI.escape(row['Client Name'])}</option>`).join('')}</select></div><div class="field"><label>نوع العمل</label><select name="jobType"><option>PHOTOGRAPHY</option><option>VIDEOGRAPHY</option><option>EDITING</option><option>DESIGN</option><option>DELIVERY</option></select></div><div class="field wide"><label>العنوان</label><input name="title" required></div><div class="field"><label>الموظف</label><select name="employeeId"><option value="">غير مسند</option>${employees.map(row => `<option value="${UI.escape(row['Employee ID'])}">${UI.escape(row['Full Name'])}</option>`).join('')}</select></div><div class="field"><label>موعد التسليم</label><input name="dueDate" type="date"></div><div class="field wide"><label>Brief</label><textarea name="brief"></textarea></div><div class="wide actions"><button class="btn btn-primary" type="submit">إنشاء العمل</button></div></form>`; }
  async function load() {
    const [{ jobs, employees = [] }, clientsResult] = await Promise.all([API.get('studio.jobs'), API.get('clients').catch(() => ({clients:[]}))]);
    UI.setMain(`<section class="grid metrics">${['TODO','IN_PROGRESS','IN_REVIEW','DONE'].map(status => UI.metric(status, UI.number(jobs.filter(row => row.Status === status).length))).join('')}</section><section class="card"><div class="card-header"><div><h2>أعمال الاستوديو</h2><p class="muted">التصوير والمونتاج والتصميم والتسليم.</p></div>${clientsResult.clients.length ? '<button class="btn btn-primary" id="new-job">عمل جديد</button>' : ''}</div>${UI.table(jobs, [{key:'Title',label:'العمل'},{key:'Job Type',label:'النوع',render:UI.badge},{key:'Assigned To',label:'المسؤول'},{key:'Due Date',label:'التسليم',render:UI.date},{key:'Status',label:'الحالة',render:UI.badge},{key:'Delivery URL',label:'رابط التسليم',render:v => v ? `<a class="lime" target="_blank" rel="noopener" href="${UI.escape(v)}">فتح الرابط</a>` : '—'}])}</section>`);
    document.querySelector('#new-job')?.addEventListener('click', () => { const modal = UI.modal('عمل استوديو جديد', form(clientsResult.clients, employees)); const target = modal.querySelector('form'); target.addEventListener('submit', event => { event.preventDefault(); UI.submit(target, async data => { await API.post('studio.jobs', data); UI.toast('تم إنشاء عمل الاستوديو.'); modal.remove(); load(); }); }); });
  }
  ANCPageModules.studio = { load };
})();
