(() => {
  function form(clients) { return `<form class="form-grid"><div class="field"><label>الاسم</label><input name="fullName" required></div><div class="field"><label>بريد Google</label><input name="email" type="email" required></div><div class="field"><label>نوع الحساب</label><select name="userType"><option>EMPLOYEE</option><option>CLIENT</option><option>ADMIN</option></select></div><div class="field"><label>الدور</label><select name="role"><option>EMPLOYEE</option><option>MANAGER</option><option>ACCOUNT_MANAGER</option><option>FINANCE</option><option>MEDIA_BUYER</option><option>CREATIVE</option><option>STUDIO</option><option>VIEWER</option></select></div><div class="field wide"><label>العميل (لحساب CLIENT)</label><select name="clientId"><option value="">غير مرتبط</option>${clients.map(row=>`<option value="${UI.escape(row['Client ID'])}">${UI.escape(row['Client Name'])}</option>`).join('')}</select></div><div class="wide actions"><button class="btn btn-primary" type="submit">إنشاء المستخدم</button></div></form>`; }
  async function load() {
    const [{ users }, { clients }] = await Promise.all([API.get('users'),API.get('clients')]);
    UI.setMain(`<section class="grid metrics">${UI.metric('إجمالي المستخدمين',users.length)}${UI.metric('الحسابات النشطة',users.filter(row=>String(row.Active)==='true'||row.Active===true).length)}${UI.metric('الموظفون',users.filter(row=>row['User Type']==='EMPLOYEE').length)}${UI.metric('العملاء',users.filter(row=>row['User Type']==='CLIENT').length)}</section><section class="card"><div class="card-header"><div><h2>إدارة المستخدمين</h2><p class="muted">الدخول متاح فقط لبريد Google المسجل والنشط.</p></div><button class="btn btn-primary" id="new-user">مستخدم جديد</button></div>${UI.table(users,[{key:'Full Name',label:'الاسم'},{key:'Email',label:'البريد'},{key:'User Type',label:'النوع',render:UI.badge},{key:'Role',label:'الدور'},{key:'Active',label:'نشط',render:UI.badge},{key:'Last Login',label:'آخر دخول',render:UI.date}])}</section>`);
    document.querySelector('#new-user').addEventListener('click',()=>{const modal=UI.modal('مستخدم جديد',form(clients));const target=modal.querySelector('form');target.addEventListener('submit',event=>{event.preventDefault();UI.submit(target,async data=>{await API.post('users',data);UI.toast('تم إنشاء المستخدم.');modal.remove();load();});});});
  }
  ANCPageModules.users = { load };
})();
